#!/bin/bash

# Quick VPS ML Dependencies Fix - Copy and Paste Commands
echo "🚀 Quick Fix for VPS ML Dependencies"
echo "==================================="
echo ""
echo "Copy and paste these commands one by one on the VPS:"
echo ""
echo "# 1. Connect to VPS"
echo "ssh root@88.222.214.26"
echo ""
echo "# 2. Navigate to project and pull latest changes"
echo "cd /var/www/dash-atm"
echo "git pull origin main"
echo ""
echo "# 3. Go to backend and activate virtual environment"
echo "cd backend"
echo "source venv/bin/activate"
echo ""
echo "# 4. Upgrade pip"
echo "pip install --upgrade pip"
echo ""
echo "# 5. Install ML dependencies (this will take 5-10 minutes)"
echo "pip install numpy>=1.24.0"
echo "pip install pandas>=2.0.0"
echo "pip install scikit-learn>=1.3.0"
echo "pip install matplotlib>=3.7.0"
echo "pip install seaborn>=0.12.0"
echo ""
echo "# 6. Install all requirements"
echo "pip install -r requirements.txt"
echo ""
echo "# 7. Verify installation"
echo "python3 -c \"import numpy, pandas, sklearn, matplotlib, seaborn; print('✅ All ML packages imported successfully!')\""
echo ""
echo "# 8. Restart PM2 main API"
echo "pm2 stop dash-atm-main-api"
echo "pm2 start dash-atm-main-api"
echo ""
echo "# 9. Check status and logs"
echo "pm2 status"
echo "pm2 logs dash-atm-main-api --lines 20"
echo ""
echo "# 10. Test API"
echo "curl http://localhost:8000/api/v1/health"
echo ""
echo "==================================="
echo "Expected result: No more numpy import errors!"
