include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    use_key_in_widget_constructors: true
